// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/container.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/container.go -destination=internal/application/mocks/mock_container_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "container-manager/internal/domain/entity"
	containerruntime "container-manager/internal/infrastructure/container_runtime"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContainerRepository is a mock of ContainerRepository interface.
type MockContainerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContainerRepositoryMockRecorder
	isgomock struct{}
}

// MockContainerRepositoryMockRecorder is the mock recorder for MockContainerRepository.
type MockContainerRepositoryMockRecorder struct {
	mock *MockContainerRepository
}

// NewMockContainerRepository creates a new mock instance.
func NewMockContainerRepository(ctrl *gomock.Controller) *MockContainerRepository {
	mock := &MockContainerRepository{ctrl: ctrl}
	mock.recorder = &MockContainerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerRepository) EXPECT() *MockContainerRepositoryMockRecorder {
	return m.recorder
}

// CreateContainer mocks base method.
func (m *MockContainerRepository) CreateContainer(ctx context.Context, userID int64, options containerruntime.ContainerCreateOptions) (*entity.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContainer", ctx, userID, options)
	ret0, _ := ret[0].(*entity.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContainer indicates an expected call of CreateContainer.
func (mr *MockContainerRepositoryMockRecorder) CreateContainer(ctx, userID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContainer", reflect.TypeOf((*MockContainerRepository)(nil).CreateContainer), ctx, userID, options)
}

// GetContainer mocks base method.
func (m *MockContainerRepository) GetContainer(ctx context.Context, id string) (*entity.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainer", ctx, id)
	ret0, _ := ret[0].(*entity.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainer indicates an expected call of GetContainer.
func (mr *MockContainerRepositoryMockRecorder) GetContainer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainer", reflect.TypeOf((*MockContainerRepository)(nil).GetContainer), ctx, id)
}

// RemoveContainer mocks base method.
func (m *MockContainerRepository) RemoveContainer(ctx context.Context, userID int64, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContainer", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContainer indicates an expected call of RemoveContainer.
func (mr *MockContainerRepositoryMockRecorder) RemoveContainer(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContainer", reflect.TypeOf((*MockContainerRepository)(nil).RemoveContainer), ctx, userID, id)
}

// StartContainer mocks base method.
func (m *MockContainerRepository) StartContainer(ctx context.Context, userID int64, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartContainer", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartContainer indicates an expected call of StartContainer.
func (mr *MockContainerRepositoryMockRecorder) StartContainer(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartContainer", reflect.TypeOf((*MockContainerRepository)(nil).StartContainer), ctx, userID, id)
}

// StopContainer mocks base method.
func (m *MockContainerRepository) StopContainer(ctx context.Context, userID int64, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainer", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainer indicates an expected call of StopContainer.
func (mr *MockContainerRepositoryMockRecorder) StopContainer(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainer", reflect.TypeOf((*MockContainerRepository)(nil).StopContainer), ctx, userID, id)
}
