// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/infrastructure/container_user.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/infrastructure/container_user.go -destination=internal/application/mocks/mock_container_user.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContainerUserRepository is a mock of ContainerUserRepository interface.
type MockContainerUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContainerUserRepositoryMockRecorder
	isgomock struct{}
}

// MockContainerUserRepositoryMockRecorder is the mock recorder for MockContainerUserRepository.
type MockContainerUserRepositoryMockRecorder struct {
	mock *MockContainerUserRepository
}

// NewMockContainerUserRepository creates a new mock instance.
func NewMockContainerUserRepository(ctrl *gomock.Controller) *MockContainerUserRepository {
	mock := &MockContainerUserRepository{ctrl: ctrl}
	mock.recorder = &MockContainerUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerUserRepository) EXPECT() *MockContainerUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockContainerUserRepository) Create(ctx context.Context, containerID string, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, containerID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockContainerUserRepositoryMockRecorder) Create(ctx, containerID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContainerUserRepository)(nil).Create), ctx, containerID, userID)
}

// Delete mocks base method.
func (m *MockContainerUserRepository) Delete(ctx context.Context, containerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, containerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContainerUserRepositoryMockRecorder) Delete(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContainerUserRepository)(nil).Delete), ctx, containerID)
}

// GetUserIDByContainerID mocks base method.
func (m *MockContainerUserRepository) GetUserIDByContainerID(ctx context.Context, containerID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByContainerID", ctx, containerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByContainerID indicates an expected call of GetUserIDByContainerID.
func (mr *MockContainerUserRepositoryMockRecorder) GetUserIDByContainerID(ctx, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByContainerID", reflect.TypeOf((*MockContainerUserRepository)(nil).GetUserIDByContainerID), ctx, containerID)
}
